/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.cloud.app.command;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.apache.commons.io.FileUtils;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.PrivilegedExecutorService;
import org.eclipse.kura.executor.UnprivilegedExecutorService;
import org.eclipse.kura.message.KuraPayload;
import org.junit.After;
import org.junit.Test;
import org.mockito.ArgumentCaptor;

public class CommandWorkingDirectoryTest {

    private static final String COMMAND = "echo test";

    private Path configuredDirectory;
    private Optional<Path> requestedDirectory = Optional.empty();

    private CommandCloudApp commandCloudApp;
    private UnprivilegedExecutorService unprivilegedExecutorService;

    private Optional<Exception> occurredException = Optional.empty();

    @Test
    public void configuredWorkingDirectoryIsUsedWhenTheRequestDoesNotCarryOne() throws IOException {
        givenConfiguredWorkingDirectory();
        givenCommandService();

        whenCommandIsExecutedIn(null);

        thenNoExceptionOccurred();
        thenCommandWasExecutedIn(this.configuredDirectory.toString());
    }

    @Test
    public void configuredWorkingDirectoryIsUsedWhenTheRequestCarriesAnEmptyOne() throws IOException {
        givenConfiguredWorkingDirectory();
        givenCommandService();

        whenCommandIsExecutedIn("");

        thenNoExceptionOccurred();
        thenCommandWasExecutedIn(this.configuredDirectory.toString());
    }

    @Test
    public void requestedWorkingDirectoryOverridesTheConfiguredOne() throws IOException {
        givenConfiguredWorkingDirectory();
        givenRequestedWorkingDirectoryOutsideTheConfiguredOne();
        givenCommandService();

        whenCommandIsExecutedIn(this.requestedDirectory.get().toString());

        thenNoExceptionOccurred();
        thenCommandWasExecutedIn(this.requestedDirectory.get().toString());
    }

    @After
    public void clean() throws IOException {
        if (this.configuredDirectory != null) {
            FileUtils.deleteDirectory(this.configuredDirectory.toFile());
        }
        if (this.requestedDirectory.isPresent()) {
            FileUtils.deleteDirectory(this.requestedDirectory.get().toFile());
        }
    }

    private void givenConfiguredWorkingDirectory() throws IOException {
        this.configuredDirectory = Files.createTempDirectory("kura-command-configured-").toRealPath();
    }

    private void givenRequestedWorkingDirectoryOutsideTheConfiguredOne() throws IOException {
        this.requestedDirectory = Optional.of(Files.createTempDirectory("kura-command-requested-").toRealPath());
    }

    private void givenCommandService() {
        this.unprivilegedExecutorService = mock(UnprivilegedExecutorService.class);
        when(this.unprivilegedExecutorService.execute(any())).thenReturn(successfulStatus());

        this.commandCloudApp = new CommandCloudApp();
        this.commandCloudApp.setUnprivilegedExecutorService(this.unprivilegedExecutorService);
        this.commandCloudApp.setPrivilegedExecutorService(mock(PrivilegedExecutorService.class));

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.enable", true);
        properties.put("command.timeout", 10);
        properties.put("command.working.directory", this.configuredDirectory.toString());

        this.commandCloudApp.updated(properties);
    }

    private void whenCommandIsExecutedIn(String requestedWorkingDirectory) {
        KuraCommandRequestPayload payload = new KuraCommandRequestPayload(COMMAND);
        payload.setWorkingDir(requestedWorkingDirectory);

        try {
            this.commandCloudApp.execute((KuraPayload) payload);
        } catch (Exception e) {
            this.occurredException = Optional.of(e);
        }
    }

    private void thenNoExceptionOccurred() {
        if (this.occurredException.isPresent()) {
            throw new AssertionError("Unexpected exception", this.occurredException.get());
        }
    }

    private void thenCommandWasExecutedIn(String expectedDirectory) {
        ArgumentCaptor<Command> executedCommand = ArgumentCaptor.forClass(Command.class);
        verify(this.unprivilegedExecutorService).execute(executedCommand.capture());

        assertEquals(expectedDirectory, executedCommand.getValue().getDirectory());
    }

    private static CommandStatus successfulStatus() {
        CommandStatus status = new CommandStatus(new Command(new String[] { COMMAND }), new LinuxExitStatus(0));
        status.setOutputStream(new ByteArrayOutputStream());
        status.setErrorStream(new ByteArrayOutputStream());

        return status;
    }
}
