/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.cloud.app.command;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.apache.commons.io.FileUtils;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.PrivilegedExecutorService;
import org.eclipse.kura.executor.UnprivilegedExecutorService;
import org.eclipse.kura.message.KuraPayload;
import org.junit.After;
import org.junit.Test;
import org.mockito.ArgumentCaptor;

public class ExtractCommandArchiveTest {

    private static final String COMMAND = "echo test";
    private static final String ENTRY_NAME = "payload.txt";
    private static final String ENTRY_CONTENT = "payload content";
    private static final String STAGING_PREFIX = "kura-command-archive-";

    private Path workingDirectory;

    private CommandCloudApp commandCloudApp;
    private UnprivilegedExecutorService unprivilegedExecutorService;
    private PrivilegedExecutorService privilegedExecutorService;

    private byte[] archive;
    private boolean privileged;
    private int mkdirExitCode;
    private int copyExitCode;
    private boolean copyTimedOut;
    private Optional<Path> stagingSeenByTheCopy = Optional.empty();
    private Optional<Set<PosixFilePermission>> stagingPermsAtCopy = Optional.empty();
    private Optional<Exception> occurredException = Optional.empty();

    @Test
    public void archiveIsUnzippedInATemporaryDirectoryAndCopiedIntoTheWorkingDirectory() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheArchiveWasUnzippedInATemporaryDirectory();
        thenTheCopyTargetedTheWorkingDirectory();
    }

    @Test
    public void theWorkingDirectoryIsCreatedBeforeTheCopy() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheWorkingDirectoryWasCreatedFirst();
    }

    @Test
    public void theCommandRunsAfterTheArchiveHasBeenCopied() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheLastExecutedCommandIsTheRequestedOne();
    }

    @Test
    public void theStagingDirectoryIsRemovedAfterTheCopy() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenNoStagingDirectoryIsLeftBehind();
    }

    @Test
    public void theCommandIsNotExecutedWhenTheWorkingDirectoryCannotBeCreated() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenFailingWorkingDirectoryCreation();
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenExceptionOccurred(KuraErrorCode.DECODER_ERROR);
        thenTheCommandWasNotExecuted();
        thenNoStagingDirectoryIsLeftBehind();
    }

    @Test
    public void aPartialCopyIsRemovedAndTheCommandIsNotExecuted() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenFailingCopy();
        givenArchiveWithEntryNamed("data/payload.txt");

        whenCommandIsExecuted();

        thenExceptionOccurred(KuraErrorCode.DECODER_ERROR);
        thenCopiedFilesWereRemoved("'data/payload.txt'");
        thenCopiedDirectoriesWereRemoved("'data'");
        thenTheCommandWasNotExecuted();
    }

    @Test
    public void thePrivilegedExecutorRunsTheWholeFlowWhenItIsSelected() throws IOException {
        givenDirectories();
        givenCommandService(true);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheUnprivilegedExecutorWasNotUsed();
        thenTheWorkingDirectoryWasCreatedFirst();
        thenTheCopyTargetedTheWorkingDirectory();
        thenTheLastExecutedCommandIsTheRequestedOne();
    }

    @Test
    public void theWorkingDirectoryAndCopyCommandsRunInAShell() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheWorkingDirectoryAndCopyCommandsRunInAShell();
    }

    @Test
    public void theStagingDirectoryIsRemovedWhenTheCopyFails() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenFailingCopy();
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenExceptionOccurred(KuraErrorCode.DECODER_ERROR);
        thenNoStagingDirectoryIsLeftBehind();
    }

    @Test
    public void theCopyIsCleanedUpAndTheCommandIsNotRunWhenTheCopyTimesOut() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenTimingOutCopy();
        givenArchiveWithEntryNamed("data/payload.txt");

        whenCommandIsExecuted();

        thenExceptionOccurred(KuraErrorCode.DECODER_ERROR);
        thenCopiedFilesWereRemoved("'data/payload.txt'");
        thenCopiedDirectoriesWereRemoved("'data'");
        thenTheCommandWasNotExecuted();
        thenNoStagingDirectoryIsLeftBehind();
    }

    @Test
    public void theCommandRunsInTheConfiguredWorkingDirectory() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheCommandRanIn(this.workingDirectory);
    }

    @Test
    public void theStagingDirectoryIsReadableByTheCommandUser() throws IOException {
        givenDirectories();
        givenCommandService(false);
        givenArchiveWithEntryNamed(ENTRY_NAME);

        whenCommandIsExecuted();

        thenNoExceptionOccurred();
        thenTheStagingDirectoryWasReadableByTheCommandUser();
    }

    @After
    public void clean() throws IOException {
        if (this.workingDirectory != null) {
            FileUtils.deleteDirectory(this.workingDirectory.toFile());
        }
    }

    private void givenDirectories() throws IOException {
        this.workingDirectory = Files.createTempDirectory("kura-test-wd-").toRealPath();
        this.mkdirExitCode = 0;
        this.copyExitCode = 0;
        this.copyTimedOut = false;
    }

    private void givenFailingWorkingDirectoryCreation() {
        this.mkdirExitCode = 1;
    }

    private void givenFailingCopy() {
        this.copyExitCode = 1;
    }

    private void givenTimingOutCopy() {
        this.copyTimedOut = true;
    }

    private void givenArchiveWithEntryNamed(String entryName) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();

        try (ZipOutputStream zos = new ZipOutputStream(bytes)) {
            zos.putNextEntry(new ZipEntry(entryName));
            zos.write(ENTRY_CONTENT.getBytes(UTF_8));
            zos.closeEntry();
        }

        this.archive = bytes.toByteArray();
    }

    private void givenCommandService(boolean privileged) {
        this.privileged = privileged;
        this.unprivilegedExecutorService = mock(UnprivilegedExecutorService.class);
        this.privilegedExecutorService = mock(PrivilegedExecutorService.class);

        when(this.unprivilegedExecutorService.execute(any()))
                .thenAnswer(invocation -> statusFor(invocation.getArgument(0)));
        when(this.privilegedExecutorService.execute(any()))
                .thenAnswer(invocation -> statusFor(invocation.getArgument(0)));

        this.commandCloudApp = new CommandCloudApp();
        this.commandCloudApp.setUnprivilegedExecutorService(this.unprivilegedExecutorService);
        this.commandCloudApp.setPrivilegedExecutorService(this.privilegedExecutorService);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.enable", true);
        properties.put("command.timeout", 10);
        properties.put("command.working.directory", this.workingDirectory.toString());
        properties.put("privileged.command.service.enable", privileged);

        this.commandCloudApp.updated(properties);
    }

    private void whenCommandIsExecuted() {
        KuraCommandRequestPayload payload = new KuraCommandRequestPayload(COMMAND);
        payload.setZipBytes(this.archive);

        try {
            this.commandCloudApp.execute((KuraPayload) payload);
        } catch (Exception e) {
            this.occurredException = Optional.of(e);
        }
    }

    private void thenNoExceptionOccurred() {
        if (this.occurredException.isPresent()) {
            throw new AssertionError("Unexpected exception", this.occurredException.get());
        }
    }

    private void thenExceptionOccurred(KuraErrorCode expectedErrorCode) {
        assertTrue(this.occurredException.isPresent());
        assertTrue(this.occurredException.get() instanceof KuraException);
        assertEquals(expectedErrorCode, ((KuraException) this.occurredException.get()).getCode());
    }

    private void thenTheArchiveWasUnzippedInATemporaryDirectory() {
        assertTrue(this.stagingSeenByTheCopy.isPresent());

        Path staging = this.stagingSeenByTheCopy.get();

        assertTrue(staging.startsWith(Paths.get(System.getProperty("java.io.tmpdir"))));
        assertTrue(staging.getFileName().toString().startsWith(STAGING_PREFIX));
    }

    private void thenTheCopyTargetedTheWorkingDirectory() {
        Command copy = commandStartingWith("cp");

        assertArrayEquals(new String[] { "cp", "-a", "--remove-destination",
                "'" + this.stagingSeenByTheCopy.get() + "/.'", "'" + this.workingDirectory + "/'" },
                copy.getCommandLine());
    }

    private void thenTheLastExecutedCommandIsTheRequestedOne() {
        List<Command> commands = executedCommands();

        assertArrayEquals(new String[] { COMMAND }, commands.get(commands.size() - 1).getCommandLine());
    }

    private void thenNoStagingDirectoryIsLeftBehind() throws IOException {
        try (Stream<Path> children = Files.list(Paths.get(System.getProperty("java.io.tmpdir")))) {
            assertEquals(0,
                    children.filter(child -> child.getFileName().toString().startsWith(STAGING_PREFIX)).count());
        }
    }

    private void thenCopiedFilesWereRemoved(String... expectedQuotedPaths) {
        String[] expected = new String[expectedQuotedPaths.length + 2];
        expected[0] = "rm";
        expected[1] = "-f";
        System.arraycopy(expectedQuotedPaths, 0, expected, 2, expectedQuotedPaths.length);

        Command cleanup = commandStartingWith("rm");

        assertArrayEquals(expected, cleanup.getCommandLine());
        assertEquals(this.workingDirectory.toString(), cleanup.getDirectory());
    }

    private void thenCopiedDirectoriesWereRemoved(String... expectedQuotedPaths) {
        String[] expected = new String[expectedQuotedPaths.length + 1];
        expected[0] = "rmdir";
        System.arraycopy(expectedQuotedPaths, 0, expected, 1, expectedQuotedPaths.length);

        assertArrayEquals(expected, commandStartingWith("rmdir").getCommandLine());
    }

    private void thenTheCommandWasNotExecuted() {
        for (Command command : executedCommands()) {
            assertNotEquals(COMMAND, command.getCommandLine()[0]);
        }
    }

    private void thenTheUnprivilegedExecutorWasNotUsed() {
        verify(this.unprivilegedExecutorService, never()).execute(any());
    }

    private void thenTheWorkingDirectoryWasCreatedFirst() {
        assertArrayEquals(new String[] { "mkdir", "-p", "'" + this.workingDirectory + "'" },
                executedCommands().get(0).getCommandLine());
    }

    private void thenTheWorkingDirectoryAndCopyCommandsRunInAShell() {
        assertTrue(commandStartingWith("mkdir").isExecutedInAShell());
        assertTrue(commandStartingWith("cp").isExecutedInAShell());
    }

    private void thenTheCommandRanIn(Path expectedDirectory) {
        Command command = executedCommands().get(executedCommands().size() - 1);

        assertArrayEquals(new String[] { COMMAND }, command.getCommandLine());
        assertEquals(expectedDirectory.toString(), command.getDirectory());
    }

    private void thenTheStagingDirectoryWasReadableByTheCommandUser() {
        assertTrue(this.stagingPermsAtCopy.isPresent());

        Set<PosixFilePermission> permissions = this.stagingPermsAtCopy.get();
        assertTrue(permissions.contains(PosixFilePermission.GROUP_READ));
        assertTrue(permissions.contains(PosixFilePermission.GROUP_EXECUTE));
        assertTrue(permissions.contains(PosixFilePermission.OTHERS_READ));
        assertTrue(permissions.contains(PosixFilePermission.OTHERS_EXECUTE));
    }

    private Command commandStartingWith(String executable) {
        for (Command command : executedCommands()) {
            if (executable.equals(command.getCommandLine()[0])) {
                return command;
            }
        }

        throw new AssertionError("No " + executable + " command was executed");
    }

    private List<Command> executedCommands() {
        ArgumentCaptor<Command> captor = ArgumentCaptor.forClass(Command.class);
        verify(this.privileged ? this.privilegedExecutorService : this.unprivilegedExecutorService, atLeastOnce())
                .execute(captor.capture());

        return captor.getAllValues();
    }

    private CommandStatus statusFor(Command command) {
        String executable = command.getCommandLine()[0];
        int exitCode = 0;
        boolean timedOut = false;

        if ("mkdir".equals(executable)) {
            exitCode = this.mkdirExitCode;
        } else if ("cp".equals(executable)) {
            exitCode = this.copyExitCode;
            timedOut = this.copyTimedOut;

            Path staging = Path.of(unquote(command.getCommandLine()[3])).getParent();
            this.stagingSeenByTheCopy = Optional.of(staging);
            capturePermissions(staging);
        }

        CommandStatus status = new CommandStatus(command, new LinuxExitStatus(exitCode));
        status.setTimedout(timedOut);
        status.setOutputStream(new ByteArrayOutputStream());
        status.setErrorStream(new ByteArrayOutputStream());

        return status;
    }

    private void capturePermissions(Path directory) {
        try {
            this.stagingPermsAtCopy = Optional.of(Files.getPosixFilePermissions(directory));
        } catch (IOException | UnsupportedOperationException e) {
            this.stagingPermsAtCopy = Optional.empty();
        }
    }

    private static String unquote(String value) {
        return value.substring(1, value.length() - 1);
    }
}
